[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0", "wheel>=0.36.0"]

[project]
authors = [
  {name = "Chukwuemeka", email = "chukwuemekaigwe05@gmail.com"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
]
dependencies = [
  # --- Core Cross-Platform Dependencies ---
  "keyboard>=0.13.5",
  "matplotlib>=3.10.8",
  "pillow>=12.1.0",
  "psutil>=7.2.1",
  "PySide6>=6.11.1",
  "requests>=2.34.2",
  "tomlkit>=0.14.0",
  # --- Windows Only Dependencies ---
  "pywin32>=311 ; sys_platform == 'win32'",
  "interception-python>=1.13.6 ; sys_platform == 'win32'",
  # --- Linux Only Dependencies ---
  "python-xlib>=0.31 ; sys_platform == 'linux'",
  "evdev>=1.7.0 ; sys_platform == 'linux'",
]
description = "A high-performance touch-to-keyboard/mouse mapper for PC gaming."
name = "Touch2Key"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[project.urls]
Homepage = "https://github.com/Chukxz/Touch2Key"

# --- Optional Development Dependencies ---
# Install these by running: pip install -e .[dev]
[project.optional-dependencies]
dev = [
  "black>=23.7.0",
  "flake8>=6.1.0",
  "pytest>=7.4.0",
  "snakeviz>=2.2.2",
  "build>=1.5.0"
]

[project.scripts]
# Primary Entry Points
touch2key = "modules.main:run"
touch2key-gui = "modules.gui.app:run"

# CLI Profile, Layout & Typematic Management
touch2key-manage = "modules.cli.manager:run"
touch2key-plot = "modules.cli.layout_plotter:run"

# Device & Network Tools
touch2key-adb = "modules.scripts.show_adb_path:run"
touch2key-capture = "modules.scripts.adb_screen_capture:run"
touch2key-wireless = "modules.cli.wireless_connect:run"

# Lifecycle & Diagnostic Scripts
touch2key-preflight = "modules.scripts.pre_flight:run"
touch2key-setup = "modules.scripts.setup:run"
touch2key-uninstall = "modules.scripts.uninstall:run"

[tool.setuptools.packages.find]
where = ["src"]

# We don't need to use "*" as we only have one top-level module.
[tool.setuptools.package-data]
"modules" = ["py.typed"]

[tool.black]
target-version = ['py310']